function [ joint_idx ] = get_joint_index(joint)
    jointNames = { ...
        'Neck','Head', ...
        'ShoulderL', 'ArmUpperL', 'LeftShoulderYaw', ...
        'ArmLowerL','LeftWristYaw','LeftWristRoll','LeftWristYaw2', ... 
        'PelvYL','PelvL','LegUpperL','LegLowerL','AnkleL','FootL',...
        'PelvYR','PelvR','LegUpperR','LegLowerR','AnkleR','FootR',...
        'ShoulderR', 'ArmUpperR', 'RightShoulderYaw','ArmLowerR',...
        'RightWristYaw','RightWristRoll','RightWristYaw2',...
        'TorsoPitch','TorsoYaw',...
        'l_wrist_grip1','l_wrist_grip2','l_wrist_grip3',...
        'r_wrist_grip1','r_wrist_grip2','r_wrist_grip3',...
        'ChestLidarPan',...
    };
    joint_idx = 1;
    for i=1:numel(jointNames)
        str = jointNames{i};
        if strncmp(str, joint, 8)==1
            joint_idx = i;
            break;
        end
    end
end